"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import Header from "@/components/Header";
import AdminGuard from "@/components/AdminGuard";

type User={username:string;password:string;role:"administrator"|"school"|"student";name:string;district?:string;schoolName?:string;suspended?:boolean};

export default function UserManagement(){
 const[users,setUsers]=useState<User[]>([]),[message,setMessage]=useState(""),[error,setError]=useState("");
 function load(){try{setUsers(JSON.parse(localStorage.getItem("helps_users")||"[]"))}catch{setUsers([])}}
 useEffect(()=>{load()},[]);
 function publish(next:User[]){localStorage.setItem("helps_users",JSON.stringify(next));setUsers(next);window.dispatchEvent(new Event("helps-data-updated"))}
 const students=useMemo(()=>users.filter(user=>user.role==="student").sort((a,b)=>a.username.localeCompare(b.username)),[users]);
 const teachers=useMemo(()=>users.filter(user=>user.role==="school").sort((a,b)=>a.username.localeCompare(b.username)),[users]);
 const personnel=useMemo(()=>users.filter(user=>user.role==="administrator").sort((a,b)=>a.username.localeCompare(b.username)),[users]);
 function resetPassword(user:User){const password=window.prompt(`Enter a new password for ${user.username}:`);if(password===null)return;if(password.length<8){setError("The new password must contain at least 8 characters.");return}publish(users.map(item=>item.username===user.username?{...item,password}:item));setError("");setMessage(`Password reset successfully for ${user.username}.`)}
 function toggleSuspension(user:User){publish(users.map(item=>item.username===user.username?{...item,suspended:!item.suspended}:item));setError("");setMessage(`${user.username} was ${user.suspended?"reactivated":"suspended"}.`)}
 function remove(user:User){if(!window.confirm(`Delete the account “${user.username}” permanently?`))return;publish(users.filter(item=>item.username!==user.username));setError("");setMessage(`Deleted ${user.username}.`)}
 function createPersonnel(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");setMessage("");const form=event.currentTarget,data=new FormData(form),username=String(data.get("username")||"").trim(),password=String(data.get("password")||"");if(users.some(user=>user.username.toLocaleLowerCase()===username.toLocaleLowerCase())){setError("That username is already registered.");return}if(password.length<8){setError("Password must contain at least 8 characters.");return}publish([...users,{name:String(data.get("name")||"").trim(),username,password,role:"administrator"}]);form.reset();setMessage(`Division Personnel administrator account “${username}” was created.`)}
 function table(title:string,subtitle:string,list:User[]){return <section className="user-table-card"><header><div><h2>{title}</h2><p>{subtitle}</p></div><strong>{list.length}</strong></header><div className="user-table-wrap"><table><thead><tr><th>Name</th><th>Username</th><th>District</th><th>School Name</th><th>Status</th><th>Account actions</th></tr></thead><tbody>{list.length?list.map(user=><tr key={user.username}><td>{user.name||"—"}</td><td><b>{user.username}</b></td><td>{user.district||"—"}</td><td>{user.schoolName||"—"}</td><td><span className={`account-status ${user.suspended?"suspended":"active"}`}>{user.suspended?"Suspended":"Active"}</span></td><td><div className="user-actions"><button onClick={()=>resetPassword(user)}>Reset</button><button className="suspend" onClick={()=>toggleSuspension(user)}>{user.suspended?"Reactivate":"Suspend"}</button><button className="delete" onClick={()=>remove(user)}>Delete</button></div></td></tr>):<tr><td className="user-table-empty" colSpan={6}>No accounts in this group.</td></tr>}</tbody></table></div></section>}
 return <AdminGuard><main className="dashboard user-management"><Header compact/><section className="user-shell"><div className="user-page-head"><div><span className="eyebrow green">Administration</span><h1>User Management</h1><p>Manage student, teacher/school, and Division Personnel accounts.</p></div></div>{error&&<p className="user-message error">{error}</p>}{message&&<p className="user-message">{message}</p>}<section className="personnel-create"><div><span className="eyebrow green">Administrator access</span><h2>Create Division Personnel</h2><p>Division Personnel accounts receive administrator privileges.</p></div><form onSubmit={createPersonnel}><label>Name<input name="name" required placeholder="Firstname Lastname"/></label><label>Username<input name="username" required minLength={4} placeholder="Choose username"/></label><label>Password<input name="password" type="password" required minLength={8} placeholder="At least 8 characters"/></label><button type="submit">Create administrator account</button></form></section>{table("Student Accounts","Registered learner accounts",students)}{table("Teacher / School Accounts","Registered teachers and school personnel",teachers)}{personnel.length>0&&table("Division Personnel","Additional administrator-privileged accounts",personnel)}</section></main></AdminGuard>;
}
