"use client";

import { CSSProperties, useEffect, useMemo, useState } from "react";

type Data={students:number;teachers:number;downloads:number;prints:number;districts:number;schools:number;totalUsers:number;months:Array<{month:string;downloads:number;prints:number}>;districtCounts:Array<{district:string;accounts:number;schools:number}>};
const empty:Data={students:0,teachers:0,downloads:0,prints:0,districts:0,schools:0,totalUsers:0,months:[],districtCounts:[]};

function useCountUp(value:number,duration=1600){const[shown,setShown]=useState(0);useEffect(()=>{let frame=0;const started=performance.now(),start=shown,difference=value-start;const tick=(now:number)=>{const progress=Math.min(1,(now-started)/duration),eased=1-Math.pow(1-progress,3);setShown(Math.round(start+difference*eased));if(progress<1)frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[value,duration]);return shown}

export default function DashboardLiveMetrics(){
  const[data,setData]=useState<Data>(empty);
  useEffect(()=>{const load=()=>fetch("/api/stats",{cache:"no-store"}).then(r=>r.json()).then(setData).catch(()=>{});load();const timer=setInterval(load,180000);return()=>clearInterval(timer)},[]);
  const animatedSchools=useCountUp(data.schools);
  const months=useMemo(()=>Array.from({length:6},(_,i)=>{const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-(5-i));const key=d.toISOString().slice(0,7),found=data.months.find(m=>m.month===key);return{label:d.toLocaleString("en",{month:"short"}),downloads:Number(found?.downloads||0),prints:Number(found?.prints||0)}}),[data.months]);
  const maximum=Math.max(1,...months.flatMap(month=>[month.downloads,month.prints]));
  const stats=[{icon:"♙",label:"Student users",value:data.students,color:"blue"},{icon:"♟",label:"Teacher/School users",value:data.teachers,color:"green-bg"},{icon:"⇩",label:"PDF downloads",value:data.downloads,color:"gold"},{icon:"♧",label:"Printed files",value:data.prints,color:"purple"}];
  const ringStyle={"--reach-target":data.schools?"313deg":"0deg"} as CSSProperties;

  return <><div className="live-badge"><i/>Live MySQL data · refreshes every 3 minutes</div><div className="stat-grid">{stats.map(stat=><article key={stat.label}><span className={`feature-icon ${stat.color}`}>{stat.icon}</span><div><small>{stat.label}</small><strong>{stat.value.toLocaleString()}</strong><em>Updated from centralized activity</em></div></article>)}</div><div className="dash-grid"><article className="panel chart-panel"><div className="panel-head"><div><strong>Resource activity</strong><span>Hover over a bar for exact counts</span></div></div><div className="legend"><span><i className="blue-dot"/>Downloads</span><span><i className="green-dot"/>Prints</span></div><div className="bars">{months.map(month=><div className="bar-group" key={month.label}><div><i className="activity-bar download-bar" data-tooltip={`${month.label}: ${month.downloads} downloads`} style={{height:`${month.downloads?Math.max(12,month.downloads/maximum*100):2}%`}}/><i className="activity-bar print-bar" data-tooltip={`${month.label}: ${month.prints} prints`} style={{height:`${month.prints?Math.max(12,month.prints/maximum*100):2}%`}}/></div><span>{month.label}</span></div>)}</div></article><article className="panel reach-panel"><div className="panel-head"><div><strong>Program reach</strong><span>Registered school accounts</span></div></div><div className="reach"><div key={`${data.schools}-${data.districts}`} className={`ring animated-reach-ring ${data.schools?"":"reset-ring"}`} style={ringStyle}><span><strong>{animatedSchools}</strong><small>Schools</small></span></div><div><p><i className="green-dot"/><span><strong>{data.districts} districts</strong><small>Centralized records</small></span></p><p><i className="gold-dot"/><span><strong>{data.totalUsers} total users</strong><small>Students and school personnel</small></span></p></div>{data.districtCounts.length>0&&<div className="district-count-list"><strong>Accounts by district</strong>{data.districtCounts.map(district=><div key={district.district}><span>{district.district}</span><b>{district.accounts}</b></div>)}</div>}</div></article></div></>;
}
