"use client";
import {useEffect,useRef,useState} from "react";
import {createPortal} from "react-dom";
import {getResourceFile} from "@/lib/resourceFiles";

type Resource={id?:string;grade:string;subject:string;title:string;pages:number;color:string;uploaded?:boolean;term?:string};
type PdfPage={getViewport:(options:{scale:number})=>{width:number;height:number};render:(options:{canvasContext:CanvasRenderingContext2D;viewport:{width:number;height:number}})=>{promise:Promise<void>}};
type PdfDocument={numPages:number;getPage:(page:number)=>Promise<PdfPage>};

export default function ResourceCard({item}:{item:Resource}){
 const[preview,setPreview]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(""),[page,setPage]=useState(1),[pages,setPages]=useState(item.pages),[turning,setTurning]=useState<"next"|"previous"|"">(""),[viewerSize,setViewerSize]=useState(0),[downloadUrl,setDownloadUrl]=useState("");
 const documentRef=useRef<PdfDocument|null>(null),leftCanvasRef=useRef<HTMLCanvasElement|null>(null),rightCanvasRef=useRef<HTMLCanvasElement|null>(null);
 useEffect(()=>{const pending=sessionStorage.getItem("helps_pending_action");if(pending?.endsWith(`:${item.title}`)&&sessionStorage.getItem("helps_session")){sessionStorage.removeItem("helps_pending_action");setPreview(true)}},[item.title]);
 useEffect(()=>{if(!preview)return;const old=document.body.style.overflow;document.body.style.overflow="hidden";const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setPreview(false)};window.addEventListener("keydown",close);return()=>{document.body.style.overflow=old;window.removeEventListener("keydown",close)}},[preview]);
 useEffect(()=>{if(!preview||!item.uploaded||!item.id)return;let active=true;let objectUrl="";setLoading(true);setError("");documentRef.current=null;(async()=>{try{const blob=await getResourceFile(item.id!);if(!blob)throw new Error("PDF file is unavailable in this browser. Please upload it again.");objectUrl=URL.createObjectURL(blob);if(active)setDownloadUrl(objectUrl);const pdfjs=await import("pdfjs-dist");pdfjs.GlobalWorkerOptions.workerSrc="/pdf.worker.min.js";const pdf=await pdfjs.getDocument({data:await blob.arrayBuffer()}).promise as unknown as PdfDocument;if(!active)return;documentRef.current=pdf;setPages(pdf.numPages);setPage(1)}catch(reason){if(active)setError(reason instanceof Error?reason.message:"Unable to open this PDF.")}finally{if(active)setLoading(false)}})();return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl)}},[preview,item.id,item.uploaded]);
 useEffect(()=>{if(!preview)return;const resize=()=>setViewerSize(value=>value+1);window.addEventListener("resize",resize);return()=>window.removeEventListener("resize",resize)},[preview]);
 useEffect(()=>{if(!preview||!item.uploaded||!documentRef.current||!rightCanvasRef.current)return;let active=true;async function renderPage(pageNumber:number,canvas:HTMLCanvasElement|null,isSpread:boolean){if(!canvas||!documentRef.current)return;const pdfPage=await documentRef.current.getPage(pageNumber),base=pdfPage.getViewport({scale:1}),totalWidth=Math.max(300,Math.min(1000,window.innerWidth-180)),availableWidth=isSpread?totalWidth/2:Math.min(880,totalWidth),availableHeight=Math.max(330,window.innerHeight-195),scale=Math.min(availableWidth/base.width,availableHeight/base.height),viewport=pdfPage.getViewport({scale});if(!active)return;canvas.width=Math.floor(viewport.width);canvas.height=Math.floor(viewport.height);const context=canvas.getContext("2d");if(context)await pdfPage.render({canvasContext:context,viewport}).promise} (async()=>{try{const spread=page>1;await Promise.all([spread?renderPage(page-1,leftCanvasRef.current,true):Promise.resolve(),renderPage(page,rightCanvasRef.current,spread)])}catch(reason){if(active)setError(reason instanceof Error?reason.message:"This PDF page could not be rendered.")}})();return()=>{active=false}},[preview,page,pages,item.uploaded,viewerSize]);
 function requireLogin(){let session=null;try{session=JSON.parse(sessionStorage.getItem("helps_session")||"null")}catch{}if(!session){sessionStorage.setItem("helps_return_to",window.location.pathname);sessionStorage.setItem("helps_pending_action",`preview:${item.title}`);window.location.href="/login/";return}setPreview(true)}
 function recordActivity(action:"download"|"print"){let activity:Array<Record<string,string>>=[];try{activity=JSON.parse(localStorage.getItem("helps_resource_activity")||"[]")}catch{}activity.push({action,title:item.title,subject:item.subject,grade:item.grade,at:new Date().toISOString()});localStorage.setItem("helps_resource_activity",JSON.stringify(activity));window.dispatchEvent(new Event("helps-data-updated"))}
 function printPdf(){if(!downloadUrl)return;recordActivity("print");const frame=document.createElement("iframe");frame.className="pdf-print-frame";frame.src=downloadUrl;document.body.appendChild(frame);frame.onload=()=>window.setTimeout(()=>{frame.contentWindow?.focus();frame.contentWindow?.print();window.setTimeout(()=>frame.remove(),1500)},350)}
 function turn(direction:"next"|"previous"){const target=direction==="next"?page+1:page-1;if(target<1||target>pages||turning)return;setTurning(direction);window.setTimeout(()=>{setPage(target);setTurning("")},240)}
 const viewer=preview?<div className="modal-backdrop pdf-flipbook-backdrop" role="dialog" aria-modal="true" onMouseDown={event=>{if(event.target===event.currentTarget)setPreview(false)}}><div className="preview-modal pdf-flipbook-modal"><div className="modal-head"><div><strong>{item.title}</strong><small>{loading?"Opening PDF…":error?"PDF unavailable":`PDF preview · ${pages} page${pages===1?"":"s"}`}</small></div><button onClick={()=>setPreview(false)} aria-label="Close">×</button></div><div className="flipbook real-flipbook">{loading?<div className="pdf-loading">Loading PDF…</div>:error?<div className="pdf-error"><strong>Unable to display this PDF</strong><span>{error}</span><small>Older uploads without a saved PDF must be uploaded again.</small></div>:item.uploaded?<><button className="page-arrow previous" disabled={page<=1} onClick={()=>turn("previous")} aria-label="Previous page">‹</button><div className={`book-spread ${page===1?"cover-only":"open-book"} ${turning?`turn-${turning}`:""}`}>{page>1&&<div className="pdf-page left-page"><canvas ref={leftCanvasRef}/><span className="sheet-page-number">{page-1}</span></div>}<div className="pdf-page right-page"><canvas ref={rightCanvasRef}/><span className="sheet-page-number">{page}</span></div></div><button className="page-arrow next" disabled={page>=pages} onClick={()=>turn("next")} aria-label="Next page">›</button><div className="page-count">{page===1?`Page 1 of ${pages}`:`Pages ${page-1}–${page} of ${pages}`}</div></>:<><div className={`paper ${turning?`turn-${turning}`:""}`}><span>{item.subject}</span><h2>{item.title}</h2><p>Learning Activity Sheet</p><div className="activity-lines"/></div><div className="page-count">Page 1 of {pages}</div></>}</div><div className="modal-actions"><button className="btn ghost dark" disabled={!downloadUrl} onClick={printPdf}>Print all PDF pages</button>{downloadUrl?<a className="btn primary" href={downloadUrl} download={`${item.title}.pdf`} onClick={()=>recordActivity("download")}>Download PDF</a>:<button className="btn primary" disabled>Download PDF</button>}</div></div></div>:null;
 return <><article className="resource-card"><div className="sheet-cover" style={{background:item.color}}><span>{item.subject}</span><strong>{item.grade}</strong><small>{item.term?`${item.term} · `:""}Learning Activity Sheet</small><div className="cover-wave"/></div><div className="resource-body"><div className="tag-row"><span className="tag">{item.subject}</span><span>{item.uploaded?"New PDF":`${item.pages} pages`}</span></div><h3>{item.title}</h3><p>Curriculum-aligned activity sheet with guided exercises and learner-friendly instructions.</p><div className="resource-actions"><button className="btn soft" onClick={requireLogin}>Preview</button><button className="icon-btn" onClick={requireLogin} aria-label={`Preview ${item.title}`}>↓</button></div></div></article>{viewer?createPortal(viewer,document.body):null}</>;
}
