"use client";
import {useEffect,useMemo,useState} from "react";
import {clearResourceFiles,deleteResourceFile} from "@/lib/resourceFiles";

type Resource={id:string;title:string;learningArea:string;gradeLevel:string;term:string;fileName:string};

export default function UploadedResourceAdmin(){
 const[resources,setResources]=useState<Resource[]>([]),[message,setMessage]=useState(""),[collapsed,setCollapsed]=useState<Set<string>>(new Set());
 function load(){try{setResources(JSON.parse(localStorage.getItem("helps_uploaded_resources")||"[]"))}catch{setResources([])}}
 useEffect(()=>{load();window.addEventListener("storage",load);window.addEventListener("helps-resources-updated",load);return()=>{window.removeEventListener("storage",load);window.removeEventListener("helps-resources-updated",load)}},[]);
 const groups=useMemo(()=>{const map=new Map<string,Resource[]>();[...resources].sort((a,b)=>a.learningArea.localeCompare(b.learningArea)||a.gradeLevel.localeCompare(b.gradeLevel,undefined,{numeric:true})||a.title.localeCompare(b.title)).forEach(resource=>{const subject=resource.learningArea||"Unclassified";map.set(subject,[...(map.get(subject)||[]),resource])});return [...map.entries()]},[resources]);
 function publish(next:Resource[]){localStorage.setItem("helps_uploaded_resources",JSON.stringify(next));setResources(next);window.dispatchEvent(new Event("helps-resources-updated"))}
 async function remove(resource:Resource){if(!window.confirm(`Delete “${resource.title}” permanently?`))return;try{await deleteResourceFile(resource.id);publish(resources.filter(item=>item.id!==resource.id));setMessage(`Deleted ${resource.title}.`)}catch{setMessage("The resource could not be deleted.")}}
 async function removeAll(){if(!resources.length)return;const deleteAllPin=process.env.NEXT_PUBLIC_DELETE_ALL_PIN;if(!deleteAllPin){setMessage("The resource deletion PIN is not configured. Contact the system administrator.");return}const pin=window.prompt("Security check: enter the administrator PIN to delete all uploaded resources.");if(pin===null)return;if(pin.trim()!==deleteAllPin){setMessage("Incorrect security PIN. No resources were deleted.");return}if(!window.confirm(`PIN accepted. Delete all ${resources.length} uploaded resources permanently? This cannot be undone.`))return;try{await clearResourceFiles();publish([]);setMessage("All uploaded resources were deleted.")}catch{setMessage("The uploaded resources could not be deleted.")}}
 function toggle(subject:string){setCollapsed(current=>{const next=new Set(current);next.has(subject)?next.delete(subject):next.add(subject);return next})}
 function collapseAll(){setCollapsed(new Set(groups.map(([subject])=>subject)))}
 return <article className="panel resource-admin-panel"><div className="resource-admin-head"><div><span className="eyebrow green">Resource management</span><h2>Uploaded Learning Resources</h2><p>Resources are sorted alphabetically by subject. Expand a subject to review or delete its PDFs.</p></div><button className="delete-all-button" disabled={!resources.length} onClick={removeAll}>Delete all resources</button></div>{resources.length>0&&<div className="resource-admin-toolbar"><span>{groups.length} subject{groups.length===1?"":"s"} · {resources.length} resource{resources.length===1?"":"s"}</span><div><button type="button" onClick={()=>setCollapsed(new Set())}>Expand all</button><button type="button" onClick={collapseAll}>Collapse all</button></div></div>}{message&&<p className={`resource-admin-message ${message.includes("could not")||message.includes("Incorrect")?"error":""}`}>{message}</p>}{resources.length?<div className="resource-subject-groups">{groups.map(([subject,items])=>{const closed=collapsed.has(subject);return <section className="resource-subject-group" key={subject}><button type="button" className="resource-subject-toggle" aria-expanded={!closed} onClick={()=>toggle(subject)}><span><strong>{subject}</strong><small>{items.length} uploaded PDF{items.length===1?"":"s"}</small></span><b aria-hidden="true">{closed?"+":"−"}</b></button>{!closed&&<div className="resource-admin-list">{items.map(resource=><div className="resource-admin-row" key={resource.id}><span className="pdf-admin-icon">PDF</span><div><strong>{resource.title}</strong><span>{resource.gradeLevel} · {resource.term}</span><small>{resource.fileName}</small></div><button onClick={()=>remove(resource)}>Delete</button></div>)}</div>}</section>})}</div>:<div className="resource-admin-empty">No uploaded PDF resources.</div>}</article>
}
